<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Test" duration-ms="366251" started-at="2019-02-12T09:13:17Z" finished-at="2019-02-12T09:19:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="366251" started-at="2019-02-12T09:13:17Z" finished-at="2019-02-12T09:19:23Z">
      <class name="com.adda.main.MainClass">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.adda.main.MainClass@75bd9247]" name="beforeMethod" is-config="true" duration-ms="10552" started-at="2019-02-12T14:43:06Z" finished-at="2019-02-12T14:43:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="AdminCreateNotice()[pri:1, instance:com.adda.main.MainClass@75bd9247]" name="AdminCreateNotice" duration-ms="50654" started-at="2019-02-12T14:43:17Z" finished-at="2019-02-12T14:44:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdminCreateNotice -->
        <test-method status="PASS" signature="UserVerifyNotice()[pri:2, instance:com.adda.main.MainClass@75bd9247]" name="UserVerifyNotice" duration-ms="18114" started-at="2019-02-12T14:44:08Z" finished-at="2019-02-12T14:44:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserVerifyNotice -->
        <test-method status="FAIL" signature="verifyMyUnit()[pri:3, instance:com.adda.main.MainClass@75bd9247]" name="verifyMyUnit" duration-ms="108808" started-at="2019-02-12T14:44:26Z" finished-at="2019-02-12T14:46:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Convinince charge of Debit Card when Amount payble is less than 2000 Checked expected [0.2] but found [110.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Convinince charge of Debit Card when Amount payble is less than 2000 Checked expected [0.2] but found [110.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at com.adda.home.MyUnit.makePayment(MyUnit.java:283)
	at com.adda.main.MainClass.verifyMyUnit(MainClass.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMyUnit -->
        <test-method status="PASS" signature="validateDirectMessage()[pri:4, instance:com.adda.main.MainClass@75bd9247]" name="validateDirectMessage" duration-ms="53411" started-at="2019-02-12T14:46:14Z" finished-at="2019-02-12T14:47:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDirectMessage -->
        <test-method status="PASS" signature="ValidateHelpdesk()[pri:5, instance:com.adda.main.MainClass@75bd9247]" name="ValidateHelpdesk" duration-ms="74692" started-at="2019-02-12T14:47:08Z" finished-at="2019-02-12T14:48:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateHelpdesk -->
        <test-method status="PASS" signature="createConversations()[pri:6, instance:com.adda.main.MainClass@75bd9247]" name="createConversations" duration-ms="60540" started-at="2019-02-12T14:48:23Z" finished-at="2019-02-12T14:49:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createConversations -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.adda.main.MainClass@75bd9247]" name="afterMethod" is-config="true" duration-ms="1416" started-at="2019-02-12T14:49:23Z" finished-at="2019-02-12T14:49:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.adda.main.MainClass -->
    </test> <!-- Test -->
  </suite> <!-- Test -->
</testng-results>
